# Generated by Django 2.2 on 2019-11-07 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Policy_id', models.IntegerField()),
                ('Date_Of_Purchase', models.CharField(max_length=255)),
                ('Customer_id', models.IntegerField()),
                ('Fuel', models.CharField(max_length=255)),
                ('Vehicle_Segment', models.CharField(max_length=255)),
                ('Premium', models.FloatField()),
                ('bodily_injury_liability', models.BooleanField(default=False)),
                ('personal_injury_protection', models.BooleanField(default=False)),
                ('property_damage_liability', models.BooleanField(default=False)),
                ('collision', models.BooleanField(default=False)),
                ('comprehensive', models.BooleanField(default=False)),
                ('Customer_Gender', models.CharField(max_length=255)),
                ('Customer_Income_Group', models.CharField(max_length=255)),
                ('Customer_Region', models.CharField(max_length=255)),
                ('Customer_Marital_Status', models.BooleanField(default=False)),
            ],
        ),
    ]
