# Generated by Django 2.2 on 2019-11-07 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_policy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='id',
        ),
        migrations.AlterField(
            model_name='policy',
            name='Policy_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
